# Generated by Django 6.0.2 on 2026-02-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(max_length=50, unique=True)),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('duration_hours', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('surge_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('booking_status', models.CharField(default='active', max_length=20)),
                ('booking_type', models.CharField(default='instant', max_length=20)),
                ('qr_code_data', models.TextField(blank=True, null=True, unique=True)),
                ('qr_code_path', models.CharField(blank=True, max_length=255, null=True)),
                ('booking_time', models.DateTimeField(blank=True, null=True)),
                ('checkin_deadline', models.DateTimeField(blank=True, null=True)),
                ('checkin_time', models.DateTimeField(blank=True, null=True)),
                ('forfeited', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ['-booking_id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('slot_id', models.AutoField(primary_key=True, serialize=False)),
                ('slot_number', models.CharField(max_length=20, unique=True)),
                ('floor', models.IntegerField()),
                ('section', models.CharField(max_length=10)),
                ('slot_type', models.CharField(default='regular', max_length=50)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('base_price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='available', max_length=20)),
                ('location_x', models.IntegerField(null=True)),
                ('location_y', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'parking_slots',
                'managed': False,
            },
        ),
    ]
